const villages = [
  {
    id: 1,
    dataId: 1,
    title: 'д.Борки',
    dataTooltip: 'Борки',
    desc: '5 июня 1942 года в Кировском районе Могилевской области прошла одна из самых крупных карательных операций нацистов на территории Беларуси во время Великой Отечественной войны. В тот день фашисты уничтожили вместе с жителями деревню Борки и несколько прилегающих к ней поселков. Были сожжены и расстреляны более 2 тыс. мирных жителей.',
    link: 'https://mogilev-region.gov.by/category/belarus-pomnit/memorialnyy-kompleks-pamyati-sozhzhennyh-dereven-mogilevskoy-oblasti-v',
    img: './image/borki.jpg',
    regionId: 1,
    class: 'circle borki',
  },
  {
    id: 2,
    dataId: 2,
    title: 'д.Чигиринка',
    dataTooltip: 'Чигиринка',
    desc: 'В мае 1942 г. подверглась нападению деревня Чигиринка. При поддержке местных коллаборцианистов, были расстреляны члены ВКП(б).',
    img: './image/voyna.jpg',
    link: 'https://www.6lib.ru/books/read/ohotniki-za-partizanami_-brigada-dirlevangera-169513?page=1',
    regionId: 1,
    class: 'circle chigirinka',
  },
  {
    id: 3,
    dataId: 3,
    title: 'д.Козуличи',
    dataTooltip: 'Козуличи',
    desc: 'Карательная акция прошла в июле 1942 г. Согласно акту ЧГК СССР нападение было совершено «немцами и полицаями Кировского гарнизона...».  Карательным отрядом  в количестве 400 человек была окружена деревня, население  в количестве 376 человек, как указано в документах было собрано около сарая, где в дальнейшем было сожжено.',
    img: './image/kozulichi.jpg',
    link: 'http://docs.historyrussia.org/ru/nodes/242297-iz-pokazaniya-svidetelya-e-p-gabrus-zhitelnitsy-der-kozulichi-kirovskogo-rayona-mogilevskoy-obl-o-zverskoy-rasprave-gitlerovtsev-s-naseleniem-der-kozulichi-11-iyunya-1942-g-23-yanvarya-1946-g',
    regionId: 1,
    class: 'circle kozulichi',
  },
  {
    id: 4,
    dataId: 4,
    title: 'г.Кировск',
    dataTooltip: 'Кировск',
    desc: 'За три с половиной года оккупации фашистами было уничтожено 2749 жилых домов, разграблено имущество машино-тракторных станций, колхозов, предприятий и учреждений. Только прямой ущерб, нанесённый захватчиками, составил 5 миллиардов 486 миллионов рублей (по курсу рубля 1940 года).На фронтах Великой Отечественной воны погибло около 3-х тысяч наших земляков.Полностью или частично было сожжено 74 населённых пункта, 8 из них так и не восстали из пепла. Сожжено живыми, расстреляно и замучено 5526 мирных жителей. Самая кровавая трагедия разыгралась 15 июня 1942 года в д.Борки. Здесь, в течение одного дня, фашистскими карателями было расстреляно и сожжено 1800 жителей. В назидание потомкам, в память о страшной трагедии, спустя 62 года, в д. Борки была возведена часовня в честь православной иконы Божьей Матери «Взыскание погибших».',
    img: './image/kirovsk.jpg',
    link: 'http://kirovsk.gov.by/istoriya',
    regionId: 1,
    class: 'circle kirovsk',
  },
  {
    id: 5,
    dataId: 5,
    title: 'д.Любоничи',
    dataTooltip: 'Любоничи',
    desc: 'Нападение на деревню состоялось в июле 1942 года. Тогда вместе с жителями д.Любоничи были расстреляны мирные жители деревнь Грибова Слобода и Власовичи. Всего было уничтожено около 260 человек ',
    img: './image/lyubonichi.jpg',
    link: 'http://kirovsk.gov.by/istoriya',
    regionId: 1,
    class: 'circle lub',
  },
  {
    id: 6,
    dataId: 6,
    title: 'д.Костричская Слобода (Кировский район)',
    dataTooltip: 'Костричская слобода',
    desc: 'В июне 1942 года фашисты предприняли  карательную операцию под кодовым названием «Орёл». Озверелые гитлеровцы полностью сожгли деревни Костричи, Костричская Слобода, Козуличи, Закриничье, Красный Пахарь, Пролетарий Кировского района, Вязень, Ореховка, Селец и Подстружье Кличевского района. Всего в Костричской Слободе было уничтожено 150 мирных жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2220',
    regionId: 1,
    class: 'circle kostr',
  },
  {
    id: 7,
    dataId: 7,
    title: 'д.Збышин',
    dataTooltip: 'Збышин',
    desc: 'С 17 по 21 1942 июня были сожжены  деревни Пируново, Виленка, Забуднянские Хутора, Немки и Збышин, где было убито 1076 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/1759',
    regionId: 1,
    class: 'circle zbyshin',
  },
  {
    id: 8,
    dataId: 8,
    title: 'д.Усакино',
    dataTooltip: 'Усакино',
    desc: 'За годы войны деревня дважды подвергалась нападению оккупантов в мае 1942 г. и феврале 1944 г. За это время было уничтожено более 100 домов, жертвами нападений стали более 80 мирных жителей',
    img: './image/usakino.jpg',
    link: 'https://ru.belarus.travel/landmarks/memorialnyi-kompleks-usakino',
    regionId: 2,
    class: 'circle usakino',
  },
  {
    id: 9,
    dataId: 9,
    title: 'д.Долгое',
    dataTooltip: 'Долгое',
    desc: 'За годы войны деревня подверглась нападению оккупантов осенью 1943 г. За это время было уничтожено около 200 домов, жертвами нападений стали более 100 мирных жителей',
    img: './image/usakino.jpg',
    link: 'http://db.narb.by/search/1248',
    regionId: 2,
    class: 'circle dolgoe',
  },
  {
    id: 10,
    dataId: 10,
    title: 'д.Бацевичи',
    dataTooltip: 'Бацевичи',
    desc: 'За годы войны деревня подверглась нападению оккупантов дважды в ферале и апреле 1942 г. За это время было уничтожено 179 домов, жертвами нападений стал 71 мирный житель.',
    img: './image/bacevichi.jpg',
    link: 'http://db.narb.by/search/1248',
    regionId: 2,
    class: 'circle bacevichi',
  },
  {
    id: 11,
    dataId: 11,
    title: 'д.Дубно',
    dataTooltip: 'Дубно',
    desc: 'В августе 1942 года деревня подверглась нападению карательного отряда. Всего было убито 120 мирных жителей',
    img: './image/usakino.jpg',
    link: 'http://db.narb.by/search/1300',
    regionId: 2,
    class: 'circle dubno',
  },
  {
    id: 12,
    dataId: 12,
    title: 'д.Лютино',
    dataTooltip: 'Лютино',
    desc: 'Деревню Лютино Бацевичского сельского Совета называют на Кличевщине «огненной». 7 апреля 1942 года эта деревня пережила страшную трагедию. 78 человека мужского населения были заживо сожжены в здании школы, остальные – в домах.',
    img: './image/lutino.jpg',
    link: 'https://mogilev-region.gov.by/news/80-let-nazad-fashisty-unichtozhili-vse-muzhskoe-naselenie-derevni-lyutino-klichevskogo-rayona',
    regionId: 2,
    class: 'circle lutino',
  },
  {
    id: 13,
    dataId: 13,
    title: 'д.Вязень',
    dataTooltip: 'Вязень',
    desc: 'Жители  деревень Вязень и Селец 140 человек – женщины, старики и дети – были расстреляны карательным батальоном Дирлевангера в августе 1942 года во время блокады «Адлер». После войны деревни не восстановились',
    img: './image/vyazen.jpg',
    link: 'https://www.belta.by/regions/view/memorialnyj-kompleks-partizanskoj-slavy-usakino-v-klichevskom-rajone-otkryli-posle-rekonstruktsii-453978-2021/',
    regionId: 2,
    class: 'circle vyazen',
  },
  {
    id: 14,
    dataId: 14,
    title: 'г.Кличев',
    dataTooltip: 'Кличев',
    desc: 'Кличевский партизанский край — зона партизанского движения на территории Белорусской ССР в годы Великой Отечественной войны. В начале 1944 года его территория превышала 3 тыс. квадратных километров. На территории Кличевского партизанского края находилось более 70 тыс. мирных жителей и 18 тыс. партизан, что и позволило дать ему название Малой Советской землей. Центром партизанского базирования стали Усакинские леса.',
    img: './image/klichev.jpg',
    link: 'https://www.belta.by/regions/view/memorialnyj-kompleks-partizanskoj-slavy-usakino-v-klichevskom-rajone-otkryli-posle-rekonstruktsii-453978-2021/',
    regionId: 2,
    class: 'circle klichev',
  },
  {
    id: 15,
    dataId: 15,
    title: 'д.Бозок',
    dataTooltip: 'Бозок',
    desc: 'Во время Великой Отечественной войны Бозок был оккупирован немецко-фашистскими войсками с конца июня 1941 года по 30 июня 1944 года. Действовала здесь подпольная антифашистская группа, рядом находилась партизанская застава. При отступлении 9 мая 1944 года оккупантами деревня была полностью сожжена, при этом было убито (расстреляно либо полностью сожжено) 496 жителей, в основном старики, женщины и дети, которые были похоронены в центре селения. ',
    img: './image/bozok.jpg',
    link: 'http://pamyat-osipovichi.by/2022/03/22/krovavye-sestry-xatyni-iz-osipovichskogo-rajona-d-bozok/',
    regionId: 3,
    class: 'circle bozok',
  },
  {
    id: 16,
    dataId: 16,
    title: 'д.Большая Горожа',
    dataTooltip: 'Большая Горожа',
    desc: 'Во время Великой Отечественной войны Большая Горожа была оккупирована немецко-фашистскими войсками с конца июня 1941 года по 29 июня 1944 года. В январе 1943 года оккупантами Большая Горожа вместе с посёлком Май была сожжена, при этом ими было убито 219 жителей деревни и 51 житель посёлка, которые впоследствии были захоронены в центре деревни в могиле жертв фашизма.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/318',
    regionId: 3,
    class: 'circle bric',
  },
  {
    id: 17,
    dataId: 17,
    title: 'д.Брицаловичи',
    dataTooltip: 'Брицаловичи',
    desc: 'Во время Великой Отечественной войны Брицаловичи были оккупированы немецко-фашистскими войсками с конца июня 1941 года по 30 июня 1944 года. Сама деревня в январе 1943 года была полностью сожжена оккупантами, убившими к тому же 702 жителей.',
    img: './image/bric2.jpg',
    link: 'http://docs.historyrussia.org/ru/nodes/330012-iz-protokola-doprosa-svidetelya-o-i-alhovik-o-sozhzhenii-nemetskimi-voyskami-d-britsalovichi-osipovichskogo-rayona-i-rasprave-s-ee-zhitelyami-15-fevralya-1949-g',
    regionId: 3,
    class: 'circle bric2',
  },
  {
    id: 18,
    dataId: 18,
    title: 'д.Лапичи',
    dataTooltip: 'Лапичи',
    desc: 'Гетто в Лапичах (лето 1941 — весна 1942) — еврейское гетто. Перед войной в деревне Лапичи было 225 еврейских домов, и евреи составляли бо́льшую часть населения. Немцы очень серьёзно относились к возможности еврейского сопротивления, и поэтому в большинстве случаев в первую очередь убивали в гетто или ещё до его создания евреев-мужчин в возрасте примерно от 15 до 50 лет — несмотря на экономическую нецелесообразность, так как это были самые трудоспособные узники. По этим соображениям немцы уже в начале июля 1941 года оцепили деревню, отобрали примерно 75 евреев — молодых мужчин и высоких подростков, избили палками, затем погнали к пристани, где был небольшой песчаный карьер, — и всех расстреляли.',
    img: './image/grodzyanka.jpg',
    link: 'https://vtoraya-literatura.com/pdf/smilovitsky_katastrofa_evreev_v_belorussii_1941-44_2000__ocr.pdf',
    regionId: 3,
    class: 'circle lapichi',
  },
  {
    id: 19,
    dataId: 19,
    title: 'д.Гродзянка',
    dataTooltip: 'Гродзянка',
    desc: 'В посёлке нацисты организовали гетто: в бараки у железнодорожной станции согнали всё еврейское население Гродзянки. 4 марта 1942 года их всех отвели на гродзянское кладбище и расстреляли. Согласно материалам Государственной Чрезвычайной комиссии по расследованию злодеяний немецко-фашистских захватчиков и их сообщников в тот день было расстреляно 149 евреев ─ жителей поселка',
    img: './image/grodzyanka.jpg',
    link: 'http://docs.historyrussia.org/ru/nodes/330012-iz-protokola-doprosa-svidetelya-o-i-alhovik-o-sozhzhenii-nemetskimi-voyskami-d-britsalovichi-osipovichskogo-rayona-i-rasprave-s-ee-zhitelyami-15-fevralya-1949-g',
    regionId: 3,
    class: 'circle grodzyanka',
  },
  {
    id: 20,
    dataId: 20,
    title: 'д.Лочин',
    dataTooltip: 'Лочин',
    desc: 'Деревня дважды подвергалась нападению в январе 1943 г., май 1944 г.Всего было уничтожено 776 человек.В числе уничтоженных - 300 человек из других населенных пунктов',
    img: './image/voyna.jpg',
    link: 'http://pamyat-osipovichi.by/tragediya-derevni-lochin/',
    regionId: 3,
    class: 'circle lochin',
  },
  {
    id: 21,
    dataId: 21,
    title: 'д.Маковье',
    dataTooltip: 'Маковье',
    desc: 'Перед войной в деревне проживало 249 человека, была сожжена в январе 1943 г. в ходе карательной операции "Франц". После войны не была восстановлена. Всего было уничтожено 229 человек',
    img: './image/makovye.jpg',
    link: 'https://mogilev-region.gov.by/news/o-tragedii-sozhzhennoy-karatelyami-derevni-makove-osipovichskogo-rayona-segodnya-napominaet',
    regionId: 3,
    class: 'circle makovye',
  },
  {
    id: 22,
    dataId: 22,
    title: 'д.Осовок',
    dataTooltip: 'Осовок',
    desc: 'Во время Великой Отечественной войны Осовок был оккупирован немецко-фашистскими войсками с конца июня 1941 года по 29 июня 1944 года; в декабре 1943 года было сожжено 2 двора и был убит 141 житель деревни и соседних поселений.',
    img: './image/makovye.jpg',
    link: 'http://pamyat-osipovichi.by/2022/07/15/tragediya-derevni-osovok-iz-protokola-doprosa-spasshegosya-zhitelya-d-g-kozachenka/',
    regionId: 3,
    class: 'circle osovok',
  },
  {
    id: 23,
    dataId: 23,
    title: 'д.Погорелое',
    dataTooltip: 'Погорелое',
    desc: 'Деревня трижды подвергалась нападению в феврале 1942 г., январья, ноябрь 1943 г.Всего было уничтожено 187 человек.',
    img: './image/pogoreloe.jpg',
    link: 'http://db.narb.by/search/3608',
    regionId: 3,
    class: 'circle pogoreloe',
  },
  {
    id: 24,
    dataId: 24,
    title: 'д.Свислочь',
    dataTooltip: 'Свислочь',
    desc: 'В Свислочи на протяжении 1941-1942 гг. находилось гетто. В 1942 году гетто  ликвидировали, было уничтожено более 700 мирных граждан',
    img: './image/svisloch.jpg',
    link: 'https://vtoraya-literatura.com/pdf/smilovitsky_katastrofa_evreev_v_belorussii_1941-44_2000__ocr.pdf',
    regionId: 3,
    class: 'circle svisloch',
  },
  {
    id: 25,
    dataId: 25,
    title: 'д.Сторонка',
    dataTooltip: 'Сторонка',
    desc: '20 января 1943 года  гитлеровцами были сожжены деревни Осы - Колёса, Белые и Парщаха Глусского района , Межное, Бортное, Старое Село, Корытное, Сторонка Осиповичского района , вместе жителями.Все деревни находились в партизанских зонах , в лесных массивах, в « треугольнике «Старые Дороги- Осиповичи-Бобруйск» и на небольшом расстоянии друг от друга. ',
    img: './image/storonka.jpg',
    link: 'http://pamyat-osipovichi.by/2018/03/28/derevnya-byvshaya-s-krasivym-nazvaniem-storonka/',
    regionId: 3,
    class: 'circle storonka',
  },
  {
    id: 26,
    dataId: 26,
    title: 'д.Тарасовичи',
    dataTooltip: 'Тарасовичи',
    desc: 'До войны в Тарасовичах проживало 635 человек.Деревня подверглась нападению в январе 1943 года. Всего было уничтожено 136 мирных жителей. После войны леревня была восстановлена',
    img: './image/storonka.jpg',
    link: 'http://db.narb.by/search/5917',
    regionId: 3,
    class: 'circle tarasovichi',
  },
  {
    id: 27,
    dataId: 27,
    title: 'д.Елизово',
    dataTooltip: 'Елизово',
    desc: '26 июня 1941 года Елизово захватили немецкие войска. Была создана полиция из местных коллаборационистов. Для устрашения немцы сразу схватили и расстреляли пять юношей-евреев.Евреев обязали нашить на одежду желтые шестиконечные звезды. Затем немцы, реализуя нацистскую программу уничтожения евреев, организовали в местечке гетто. Узников ежедневно использовали на принудительных тяжелых работах. 21 января 1942 года прибывший в Елизово карательный отряд немцев вместе с местными полицаями согнали 27 последних ещё живых мужчин-евреев в лес на окраине посёлка. Их заставили вырыть яму, затем раздеться, подводили к яме и расстреливали.',
    img: './image/elizovo.jpg',
    link: 'https://vtoraya-literatura.com/pdf/smilovitsky_katastrofa_evreev_v_belorussii_1941-44_2000__ocr.pdf',
    regionId: 3,
    class: 'circle elizovo',
  },
  {
    id: 28,
    dataId: 28,
    title: 'д.Ясень',
    dataTooltip: 'Ясень',
    desc: 'В Ясене на протяжении 1941-1942 гг. находилось гетто.Было убиты около 150 евреев',
    img: './image/jasen.jpg',
    link: 'https://vtoraya-literatura.com/pdf/smilovitsky_katastrofa_evreev_v_belorussii_1941-44_2000__ocr.pdf',
    regionId: 3,
    class: 'circle jasen',
  },
  {
    id: 29,
    dataId: 29,
    title: 'г.Осиповичи',
    dataTooltip: 'Осиповичи',
    desc: 'В Осиповичах на протяжении 1941-1942 гг. находилось гетто. Оно располагалось на  следующих улицах Коммунистическая, Чумакова, Октябрьская, Горького, Рабоче-крестьянская, Полевая, Калинина, Серова от улицы Р. Люксембург до улицы В. Хоружей и полностью улицы К. Либкнехта, Абросимова (бывшая Красноармейская), Социалистическая, Революционная, К. Маркса, Промышленная, Протасевичская.Было убито не менее 440 евреев.',
    img: './image/osipovichi.jpg',
    link: 'https://vtoraya-literatura.com/pdf/smilovitsky_katastrofa_evreev_v_belorussii_1941-44_2000__ocr.pdf',
    regionId: 3,
    class: 'circle osipovichi',
  },
  {
    id: 30,
    dataId: 30,
    title: 'д.Дарагоново',
    dataTooltip: 'Дараганово',
    desc: 'В Дараганово на протяжении 1941-1942 гг. находилось гетто.Было убиты около 156 евреев',
    img: './image/daraganovo.jpg',
    link: 'https://club.berkovich-zametki.com/?p=44908',
    regionId: 3,
    class: 'circle daraganovo',
  },
  {
    id: 31,
    dataId: 31,
    title: 'д.Каменка',
    dataTooltip: 'Каменка',
    desc: 'Деревня Каменка находится в 12 километрах от города Бобруйска. Эти километры в годы Великой Отечественной войны стали последними для нескольких тысяч бобруйчан, которые прошли свой трагический путь до места своей гибели. В ночь с 6 на 7 ноября 1941 года фашистами было расстреляно возле д. Каменка Бобруйского района более 10 тысяч узников ггородского еврейского гетто. Из бобруйского гетто пригнали мужчин, женщин, стариков, детей. Перед этим сюда привезли 500 военнопленных из концлагеря, расположенном в Бобруйской крепости. Их заставили вырыть 2 десятиметровых рва, а после расстреляли. Эти ямы стали братскими могилами для евреев и военнопленных. Теперь место расстрела мирных бобруйских жителей входит в границы территории деревни Слободка.',
    img: './image/kamenka.jpg',
    link: 'https://wiki.bobr.by/%D0%9A%D0%B0%D0%BC%D0%B5%D0%BD%D0%BA%D0%B0,_%D0%BC%D0%B5%D0%BC%D0%BE%D1%80%D0%B8%D0%B0%D0%BB',
    regionId: 4,
    class: 'circle kamenka',
  },
  {
    id: 32,
    dataId: 32,
    title: 'г.Бобруйск',
    dataTooltip: 'Бобруйск',
    desc: 'По данным ЧГК СССР, на территории города Бобруйска за 3 года оккупации было уничтожено около 80000 человек. Основными местами уничтожения мирного населения и военнопленных в г.Бобруйске были: деревня Каменка (военный объект №152), деревня Еловики, урочище «Лысая Гора», в Бобруйской крепости, и на ул. Парковой находились лагеря военнопленных, еврейское кладбище города Бобруйска было также местом массового истребления советских граждан.',
    img: './image/bobrujsk.jpg',
    link: 'https://wiki.bobr.by/%D0%92_%D0%B3%D0%BE%D0%B4%D1%8B_%D0%BE%D0%BA%D0%BA%D1%83%D0%BF%D0%B0%D1%86%D0%B8%D0%B8_1941-1944_%D0%B3%D0%B3.',
    regionId: 4,
    class: 'circle bobr',
  },
  {
    id: 33,
    dataId: 33,
    title: 'д.Панкратовичи',
    dataTooltip: 'Панкратовичи',
    desc: 'За годы войны  в деревне было убито 85 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/5961',
    regionId: 4,
    class: 'circle tarasovichi',
  },
  {
    id: 34,
    dataId: 34,
    title: 'д.Прудище',
    dataTooltip: 'Прудище',
    desc: 'В ноябре 1943 года в деревню Прудище, где до войны проживало 90 человек, приехали каратели. Они подожгли дома – сгорели почти все. Из 22-х домов остались только три. 30 жителей деревни погибли. .',
    img: './image/voyna.jpg',
    link: 'https://wiki.bobr.by/%D0%92_%D0%B3%D0%BE%D0%B4%D1%8B_%D0%BE%D0%BA%D0%BA%D1%83%D0%BF%D0%B0%D1%86%D0%B8%D0%B8_1941-1944_%D0%B3%D0%B3.',
    regionId: 4,
    class: 'circle prud',
  },
  {
    id: 35,
    dataId: 35,
    title: 'д.Малимоны',
    dataTooltip: 'Малимоны',
    desc: 'В декабре 1943 года деревню окружили немцы. Они врывались в крестьянские хаты и выбрасывали людей на улицы. Затем прикладами сгоняли их в сарай. Каратели обложили сарай соломой, облили все бензином и подожгли. Людей сжигали заживо. Многие пытались вырваться из огня. Тех, кому все-таки удавалось это сделать, эсэсовцы расстреливали из автоматов. Сегодня о той страшной трагедии напоминает могила жертв войны, расположенная в деревне Малимоны, и возвышающаяся над ней высокая стела — «Мать с ребенком на руках». На черных плитах высечены имена 120 жителей деревни, 60 из которых — дети',
    img: './image/malimony.jpg',
    link: 'http://svetlogorsk.by/ru/posts/2021/march/pamyati-sozhzhennyh-dereven/',
    regionId: 5,
    class: 'circle malimony',
  },
  {
    id: 36,
    dataId: 36,
    title: 'д.Ола',
    dataTooltip: 'Ола',
    desc: '14 января 1944 года деревню со всех сторон окружил немецкий карательный отряд. Под предупреждающие выстрелы мирных жителей согнали в большой колхозный сарай, затем забирая отдельными группами, отводили в другой конец деревни, заталкивали в дома и поджигали. Так за один день было убито 1758 человек, среди которых 950 детей.',
    img: './image/malimony.jpg',
    link: 'http://svetlogorsk.by/ru/posts/2021/march/pamyati-sozhzhennyh-dereven/',
    regionId: 5,
    class: 'circle ola',
  },
  {
    id: 37,
    dataId: 37,
    title: 'д.Хутор',
    dataTooltip: 'Хутор',
    desc: '14 июня 1943 года в д.Хутор неожиданно нагрянули фашисты. Захватив населенный пункт, они согнали всех жителей (в основном женщин и детей) в сарай и подожгли его. Тех, кому все-таки удавалось бежать, расстреливали на месте. Всего в тот день было сожжено и расстреляно около сотни мирных жителей.',
    img: './image/hutor.jpg',
    link: 'http://svetlogorsk.by/ru/posts/2021/march/pamyati-sozhzhennyh-dereven/',
    regionId: 5,
    class: 'circle hutor',
  },
  {
    id: 38,
    dataId: 38,
    title: 'д.Вежны',
    dataTooltip: 'Вежны',
    desc: 'До войны в Вежнах проживало 487 жителей. Деревня подверглась нападению в июне 1944 года, было убито 70 мирных жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/829',
    regionId: 5,
    class: 'circle vezny',
  },
  {
    id: 39,
    dataId: 39,
    title: 'д.Островчицы',
    dataTooltip: 'Островчицы',
    desc: 'До войны в Вежнах проживало 500 жителей. Деревня подверглась нападению в феврале 1944 года, было убито 260 мирных жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/829',
    regionId: 5,
    class: 'circle ostrov',
  },
  {
    id: 40,
    dataId: 40,
    title: 'д.Печищи',
    dataTooltip: 'Печищи',
    desc: 'Летом 1941 года Печищи заняли части вермахта. 10 февраля 1942 года немецкие каратели ворвались в деревню, сожгли её и расстреляли 120 евреев. Место расстрела находится в 1 км на север от деревни через дорогу от православного кладбища в 20 м от дороги.',
    img: './image/pechishhi.jpg',
    link: 'http://db.narb.by/search/829',
    regionId: 5,
    class: 'circle pech',
  },
  {
    id: 41,
    dataId: 41,
    title: 'д.Николаевка',
    dataTooltip: 'Николаевка',
    desc: 'В июне 1944 года оккупанты сожгли 68 дворов и убили 65 жителей. ',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/8877',
    regionId: 5,
    class: 'circle nikolaev',
  },
  {
    id: 42,
    dataId: 42,
    title: 'д.Рудня',
    dataTooltip: 'Рудня',
    desc: 'В июле 1941 года оккупанты полностью сожгли деревню и убили 8 жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/8877',
    regionId: 5,
    class: 'circle rudnya',
  },
  {
    id: 43,
    dataId: 43,
    title: 'д.Раковичи',
    dataTooltip: 'Раковичи',
    desc: 'За годы войны  в деревне было убито 86 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3910',
    regionId: 5,
    class: 'circle rakov',
  },
  {
    id: 44,
    dataId: 44,
    title: 'д.Высокий Полк',
    dataTooltip: 'Высокий Полк',
    desc: 'Здесь находится  захоронение евреев. Когда в 1941 году немцы заняли Паричи, свое вступление в городской поселок они ознаменовали жестокой расправой над еврейским населением. Немцы нашили всем евреям желтые шестиконечные звезды, а затем согнали их в один квартал, обнесенный колючей проволокой. А 18 октября 1941 года вывезли их на машинах за Высокий Полк, где после зверских пыток и издевательств расстреляли (более 1700 евреев). В феврале 1944 года, когда немецко-фашистские захватчики бежали, чтобы замести свои следы, они разрыли захоронение и сожгли его. Поэтому сегодня очень трудно установить точное количество захороненных в могиле граждан.',
    img: './image/vysokijpolk.jpg',
    link: 'http://svetlogorsk.by/ru/posts/2021/march/pamyati-sozhzhennyh-dereven/',
    regionId: 5,
    class: 'circle vyskoiy',
  },
  {
    id: 45,
    dataId: 45,
    title: 'г.п. Паричи',
    dataTooltip: 'Паричи',
    desc: 'В начале июля 1941 года немецкие войска захватили Паричи. 18 октября 1941 года оккупанты расстреляли 872 еврея (похоронены в могиле жертв фашизма, в 1,5 км от Паричей), а всего гитлеровцы за время оккупации убили 1700 человек.',
    img: './image/parichi.jpg',
    link: 'http://svetlogorsk.by/ru/posts/2021/march/pamyati-sozhzhennyh-dereven/',
    regionId: 5,
    class: 'circle parichi',
  },
  {
    id: 46,
    dataId: 46,
    title: 'д.Бобровичи',
    dataTooltip: 'Бобровичи',
    desc: 'За годы войны  в деревне было убито 89 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6182',
    regionId: 6,
    class: 'circle bobrovichi',
  },
  {
    id: 47,
    dataId: 47,
    title: 'д.Жолвинец',
    dataTooltip: 'Жолвинец',
    desc: 'За годы войны  в деревне было убито 68 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6169',
    regionId: 6,
    class: 'circle zholv',
  },
  {
    id: 48,
    dataId: 48,
    title: 'д.Заелица',
    dataTooltip: 'Заелица',
    desc: 'За годы войны в деревне было убито 150 мирных жителей.',
    img: './image/zaelica.jpg',
    link: 'http://db.narb.by/search/6169',
    regionId: 6,
    class: 'circle zaelica',
  },
  {
    id: 49,
    dataId: 49,
    title: 'д.Замосточье',
    dataTooltip: 'Замосточье',
    desc: 'За годы войны в деревне было убито 95 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6169',
    regionId: 6,
    class: 'circle zamost',
  },
  {
    id: 50,
    dataId: 50,
    title: 'д.Зеленковичи',
    dataTooltip: 'Зеленковичи',
    desc: 'За годы войны в деревне было убито 61 мирный житель.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6169',
    regionId: 6,
    class: 'circle zelenkov',
  },
  {
    id: 51,
    dataId: 51,
    title: 'д.Холопеничи',
    dataTooltip: 'Холопеничи',
    desc: 'За годы войны в деревне было убито 55 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/4933',
    regionId: 6,
    class: 'circle cholop',
  },
  {
    id: 52,
    dataId: 52,
    title: 'Глуск',
    dataTooltip: 'Глуск',
    desc: 'От рук оккупантов на территории Глусского района погибли 3126 мирных граждан, 1482 были угнаны на принудительные работы в Германию. Деревни Парщаха, Осы, Колесы, Белые, Мосты, Толстый Лес, сожженные вместе с жителями, повторили трагическую судьбу Хатыни. В декабре 1941 года на Мыслочанской горе были расстреляны более 2000 евреев и военнопленных.',
    img: './image/glusk.jpg',
    link: 'https://www.glusk.gov.by/pamiatniki',
    regionId: 6,
    class: 'circle glusk',
  },
  {
    id: 53,
    dataId: 53,
    title: 'д.Альбинск',
    dataTooltip: 'Альбинск',
    desc: 'До войны в  Альбинске проживало 500 жителей. В апреле 1942 года каратели сожгли деревню и убили 137 жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/54',
    regionId: 7,
    class: 'circle albinsk',
  },
  {
    id: 54,
    dataId: 54,
    title: 'д.Булков',
    dataTooltip: 'Булков',
    desc: 'За годы войны в деревне было убито 88 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/54',
    regionId: 7,
    class: 'circle bulkov',
  },
  {
    id: 55,
    dataId: 55,
    title: 'д.Гороховищи',
    dataTooltip: 'Гороховищи',
    desc: 'За годы войны в деревне было убито 120 мирных жителей.',
    img: './image/voyna.jpg',
    link: 'https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D1%85%D0%BE%D0%B2%D0%B8%D1%89%D0%B8_(%D0%9E%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C%D1%81%D0%BA%D0%B8%D0%B9_%D1%80%D0%B0%D0%B9%D0%BE%D0%BD)',
    regionId: 7,
    class: 'circle goroh',
  },
  {
    id: 56,
    dataId: 56,
    title: 'д.Затишье',
    dataTooltip: 'Затишье',
    desc: 'За годы войны в деревне было убито 64 мирных жителя.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/1730',
    regionId: 7,
    class: 'circle zatish',
  },
  {
    id: 57,
    dataId: 57,
    title: 'д. Иванищевичи',
    dataTooltip: 'Иванищевичи',
    desc: 'За годы войны в деревне было убито 83 мирных жителя.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/1822',
    regionId: 7,
    class: 'circle ivan',
  },
  {
    id: 58,
    dataId: 58,
    title: 'д. Карпиловка',
    dataTooltip: 'Карпиловка',
    desc: 'За годы войны в деревне было убито 326 мирных жителя, все дворы были уничтожены. После войны деревня была восстановлена',
    img: './image/karpilovka.jpg',
    link: 'http://milglory.gomel.museum.by/node/57688#:~:text=%D0%9A%D0%B0%D1%80%D0%BF%D0%B8%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0%20%E2%80%93%20%D0%B1%D1%8B%D0%B2%D1%88%D0%B0%D1%8F%20%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BD%D1%8F%20%D0%B2%20%D1%81%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B5,%D0%B2%D0%BE%D0%B9%D0%BD%D1%8B%20%E2%80%93%20%D1%81%20%D0%BE%D1%81%D0%B5%D0%BD%D0%B8%201941%20%D0%B3.',
    regionId: 7,
    class: 'circle karpilovka',
  },
  {
    id: 59,
    dataId: 59,
    title: 'д. Ковали',
    dataTooltip: 'Ковали',
    desc: 'Во время войны 2 апреля 1944 года немецкие оккупанты полностью сожгли деревню и убили 720 жителей, многие из соседних деревень. Позже каратели убили еще 141 жителя (похоронены в могилах жертв фашизма в 150 м на северо-запад и 0,8 км на запад от деревни).',
    img: './image/karpilovka.jpg',
    link: 'http://db.narb.by/search/2051',
    regionId: 7,
    class: 'circle kovali',
  },
  {
    id: 60,
    dataId: 60,
    title: 'д. Курин',
    dataTooltip: 'Курин',
    desc: 'Немецкие оккупанты в апреле 1942 года полностью сожгли деревню, расстреляли и сожгли 601 жителя (похоронены в могилах жертв фашизма в 0,7 км на юго-запад и в 1 км на юг от деревни).',
    img: './image/karpilovka.jpg',
    link: 'http://db.narb.by/search/2428',
    regionId: 7,
    class: 'circle kurin',
  },
  {
    id: 61,
    dataId: 61,
    title: 'д. Лавстыки',
    dataTooltip: 'Лавстыки',
    desc: 'Во время войны немецкие оккупанты в начале апреля 1942 года полностью сожгли деревню, расстреляли и сожгли 800 жителей, в том числе из близлежащих деревень (похоронены в могилах жертв фашизма в центре и в 0,2 км на юго-запад от деревни)',
    img: './image/karpilovka.jpg',
    link: 'http://db.narb.by/search/2456',
    regionId: 7,
    class: 'circle lavs',
  },
  {
    id: 62,
    dataId: 62,
    title: 'д. Ломовичи',
    dataTooltip: 'Ломовичи',
    desc: 'Во  войны оккупанты в апреле 1942 года сожгли 42 двора, убили 157 жителей. ',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2601',
    regionId: 7,
    class: 'circle lomovichi',
  },
  {
    id: 63,
    dataId: 63,
    title: 'д. Любань',
    dataTooltip: 'Любань',
    desc: 'Во  войны оккупанты в апреле 1942 года сожгли 5 дворов, убили 85 жителей. ',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2668',
    regionId: 7,
    class: 'circle lyuban',
  },
  {
    id: 64,
    dataId: 64,
    title: 'д. Лясковчи',
    dataTooltip: 'Лясковичи',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты 5 февраля 1942 года убили 112 жителей (похоронены в двух могилах жертв фашизма около школы), в апреле 1942 года сожгли 52 двора и убили 171 жителя, а 5 февраля 1944 года убили ещё 60 жителей. ',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2691',
    regionId: 7,
    class: 'circle lyask',
  },
  {
    id: 65,
    dataId: 65,
    title: 'д. Микуль',
    dataTooltip: 'Микуль',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты в апреле 1942 года полностью сожгли деревню и убили 67 жителей. В 1944 году оккупанты создали поблизости от деревни, на болоте, концлагерь для гражданского населения.',
    img: './image/mikul.jpg',
    link: 'http://db.narb.by/search/2885',
    regionId: 7,
    class: 'circle mikul',
  },
  {
    id: 66,
    dataId: 66,
    title: 'д. Поречье',
    dataTooltip: 'Поречье',
    desc: 'В апреле 1942 года каратели сожгли 13 дворов и убили 169 жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2885',
    regionId: 7,
    class: 'circle porech',
  },
  {
    id: 67,
    dataId: 67,
    title: 'д. Протасы',
    dataTooltip: 'Протасы',
    desc: ' Каратели в апреле 1942 года сожгли 105 дворов и убили 64 жителя. ',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3796',
    regionId: 7,
    class: 'circle protasy',
  },
  {
    id: 68,
    dataId: 68,
    title: 'д. Пружинище',
    dataTooltip: 'Пружинище',
    desc: 'В апреле 1942 года каратели полностью сожгли деревню и убили 111 жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3821',
    regionId: 7,
    class: 'circle pruzh',
  },
  {
    id: 69,
    dataId: 69,
    title: 'д. Рудня',
    dataTooltip: 'Рудня',
    desc: 'Рудня – деревня, входившая в состав Октябрьского района Гомельской области.Немецко-фашистские захватчики ворвались в Октябрьский район 29. 07.1941 г. С 1 по 05.04.1942 г. немцами было истреблено 6500 человек и сожжено 13 деревень, среди них: Подгать, Повстяки, Ковали, Вежин, Рудня, Гадунь и Смуга.Деревня Рудня была сожжена 2 апреля 1942 г. в ходе карательной операции.Деревня Рудня не была восстановлена после войны.',
    img: './image/rudnya.jpg',
    link: 'http://milglory.gomel.museum.by/node/56790',
    regionId: 7,
    class: 'circle rudn',
  },
  {
    id: 70,
    dataId: 70,
    title: 'д. Селище',
    dataTooltip: 'Селище',
    desc: 'Селище – деревня в Ломовичском сельсовете Октябрьского района Гомельской области.01.04.1942 г. гитлеровцы окружили Октябрьский район Гомельской области. Не обнаружив партизан, успевших выйти из окружения, они начали жечь деревни. По данным партизан, каратели убили 6.500 человек, сожгли дотла 13 сел. Среди этих деревень была и Селище.В деревне было сожжено 29 дворов и убито 95 жителей.Не восстановилась, увековечена в мемориальном комплексе «Хатынь».',
    img: './image/voyna.jpg',
    link: 'http://milglory.gomel.museum.by/node/56874',
    regionId: 7,
    class: 'circle selische',
  },
  {
    id: 71,
    dataId: 71,
    title: 'д. Смуга',
    dataTooltip: 'Смуга',
    desc: 'Смуга – деревня, входившая в состав Октябрьского района Гомельской области.Немецко-фашистские захватчики ворвались в Октябрьский район 29. 07.1941 г. С 1 по 05.04.1942 г. немцами было истреблено 6500 человек и сожжено 13 деревень, среди них: Подгать, Повстяки, Ковали, Вежин, Рудня, Гадунь и Смуга.Деревня Рудня не была восстановлена после войны.',
    img: './image/voyna.jpg',
    link: 'http://milglory.gomel.museum.by/node/56789',
    regionId: 7,
    class: 'circle smuga',
  },
  {
    id: 72,
    dataId: 72,
    title: 'д. Перекалье',
    dataTooltip: 'Перекалье',
    desc: 'В апреле 1942 года немецко-фашистские захватчики во время карательной операции сожгли деревню вместе с жителями, 76 человек, 27 дворов.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3478',
    regionId: 7,
    class: 'circle perekalle',
  },
  {
    id: 73,
    dataId: 73,
    title: 'д. Хоромцы',
    dataTooltip: 'Хоромцы',
    desc: 'В апреле 1942 года каратели сожгли 111 дворов и убили 233 жителя, в 1944 году убили ещё 207 жителей (похоронены в могиле жертв фашизма в центре деревни).',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/4950',
    regionId: 7,
    class: 'circle choromcy',
  },
  {
    id: 74,
    dataId: 74,
    title: 'д.Шкава',
    dataTooltip: 'Шкава',
    desc: 'Во время Великой Отечественной войны в апреле 1942 немецкие оккупанты сожгли 36 дворов и убили 69 жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/5147',
    regionId: 7,
    class: 'circle shkava',
  },
  {
    id: 75,
    dataId: 75,
    title: 'д.Осово',
    dataTooltip: 'Осово',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 75 дворов и убили 127 жителей.В настоящее время д. Осово является центром колхоза "Парижская Коммуна"',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3349',
    regionId: 8,
    class: 'circle osovost',
  },
  {
    id: 76,
    dataId: 76,
    title: 'д.Пастовичи',
    dataTooltip: 'Пастовичи',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 74 двора и убили 46 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/5615',
    regionId: 8,
    class: 'circle pastovichi',
  },
  {
    id: 77,
    dataId: 77,
    title: 'г.Старые Дороги',
    dataTooltip: 'Старые Дороги',
    desc: 'В 1941 году проживавшие в городе и окрестностях евреи были заключены в гетто, некоторым удалось сбежать из лагеря, некоторым из поезда. 19 января 1942 года была произведена массовая казнь евреев. В мае 1995 года местными властями установлен памятник «Жертва фашизма» («Реквием»).Всего от рук захватчиков погибло около 4 тысяч жителей района.',
    img: './image/voyna.jpg',
    link: 'https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D1%80%D1%8B%D0%B5_%D0%94%D0%BE%D1%80%D0%BE%D0%B3%D0%B8',
    regionId: 8,
    class: 'circle stardorogi',
  },
  {
    id: 78,
    dataId: 78,
    title: 'д.Загалье',
    dataTooltip: 'Загалье',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 71 двор и убили 45 жителей',
    img: './image/zagalye.jpg',
    link: 'http://db.narb.by/search/1530',
    regionId: 9,
    class: 'circle zagalye',
  },
  {
    id: 79,
    dataId: 79,
    title: 'д.Осовец',
    dataTooltip: 'Осовец',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 113 дворов и убили 45 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/1530',
    regionId: 9,
    class: 'circle osovets',
  },
  {
    id: 80,
    dataId: 80,
    title: 'д.Пласток',
    dataTooltip: 'Пласток',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 72 двора и убили 36 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6321',
    regionId: 9,
    class: 'circle plastok',
  },
  {
    id: 81,
    dataId: 81,
    title: 'д.Старосек',
    dataTooltip: 'Старосек',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 82 двора и убили 30 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6321',
    regionId: 9,
    class: 'circle starosek',
  },
  {
    id: 82,
    dataId: 82,
    title: 'г.Любань',
    dataTooltip: 'Любань',
    desc: 'Любанский район был оккупирован в конце июня 1941 г. Городской поселок Любань с первых дней оккупации был превращен оккупационными властями в немецко-полицейский гарнизон. Почти весь поселок был обнесен колючей проволокой, на дорогах, которые вели из Любани, стояла охрана, был введен комендантский час. Часть улиц и переулков были превращены в гетто. В Любани гетто создано в августе 1941 г. Почти все узники Любанского гетто (770 узника из 771 узников) были уничтожены 4 декабря 1941 года.',
    img: './image/voyna.jpg',
    link: 'https://lyuban.gov.by/ru/genocid/',
    regionId: 9,
    class: 'circle luban',
  },
  {
    id: 83,
    dataId: 83,
    title: 'г.п.Уречье',
    dataTooltip: 'Уречье',
    desc: 'В г.п. Уречье гетто создано в марте 1942 г. (1039 узников), 8 мая  1942 года  каратели  в лесу севернее Уречья с левой стороны Слуцкого шоссе убили 830 узников гетто. 1 августа 1942 года рядом с этим местом были расстреляны ещё 116 евреев, 4 августа 1943 г. убиты последние 93 узника на территории Уречского гетто.',
    img: './image/lyuban.jpg',
    link: 'https://lyuban.gov.by/ru/genocid/',
    regionId: 9,
    class: 'circle urechye',
  },
  {
    id: 84,
    dataId: 84,
    title: 'д.Ананчицы',
    dataTooltip: 'Ананчицы',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 184 двора и убили 55 жителей',
    img: './image/lyuban.jpg',
    link: 'http://db.narb.by/search/65',
    regionId: 10,
    class: 'circle anan',
  },
  {
    id: 85,
    dataId: 85,
    title: 'д.Домановичи',
    dataTooltip: 'Домановичи',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 142 двора и убили 267 жителей',
    img: './image/domanovichi.jpg',
    link: 'https://esoligorsk.by/novosti/v-soligorske/52857-pravedniki-iz-domanovichej-kak-semya-iz-soligorskogo-rajona-spasla-ot-fashistov-evrejskuyu-devushku',
    regionId: 10,
    class: 'circle domanovichi',
  },
  {
    id: 86,
    dataId: 86,
    title: 'д.Забродье',
    dataTooltip: 'Забродье',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 64 двора и убили 215 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/1515',
    regionId: 10,
    class: 'circle zabrodye',
  },
  {
    id: 87,
    dataId: 87,
    title: 'д.Заглинное',
    dataTooltip: 'Заглинное',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 34 двора и убили 105 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/1534',
    regionId: 10,
    class: 'circle zaglin',
  },
  {
    id: 88,
    dataId: 88,
    title: 'д.Копацевичи',
    dataTooltip: 'Копацевичи',
    desc: 'В деревне Копацевичи в феврале 1943 года убито 426 человек, в том числе 200 детей до 16 лет, разрушены все 126 дворов.',
    img: './image/kopacevichi.jpg',
    link: 'http://db.narb.by/search/1940',
    regionId: 10,
    class: 'circle kopacevichi',
  },
  {
    id: 89,
    dataId: 89,
    title: 'д.Кочева',
    dataTooltip: 'Кочева',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 43 двора и убили 75 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2236',
    regionId: 10,
    class: 'circle kocheva',
  },
  {
    id: 90,
    dataId: 90,
    title: 'д.Новые Величковичи',
    dataTooltip: 'Новые Величковичи',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 66 дворов и убили 222 жителя',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3195',
    regionId: 10,
    class: 'circle newvel',
  },
  {
    id: 91,
    dataId: 91,
    title: 'д.Писаревичи',
    dataTooltip: 'Писаревичи',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 53 двора и убили 220 жителей',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3550',
    regionId: 10,
    class: 'circle pisarev',
  },
  {
    id: 92,
    dataId: 92,
    title: 'г.п Старобин',
    dataTooltip: 'Старобин',
    desc: 'Поселок Старобин находился под немецкой оккупацией три года — с 26 июня 1941 года до 29 июня 1944 года.После оккупации евреи Старобина оказались в гетто. Было убито несколько сот человек',
    img: './image/voyna.jpg',
    link: 'https://ru.wikipedia.org/wiki/%D0%A5%D0%BE%D0%BB%D0%BE%D0%BA%D0%BE%D1%81%D1%82_%D0%B2_%D0%A1%D0%BE%D0%BB%D0%B8%D0%B3%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%BC_%D1%80%D0%B0%D0%B9%D0%BE%D0%BD%D0%B5#CITEREF%C2%AB%D0%9F%D0%B0%D0%BC%D1%8F%D1%86%D1%8C._%D0%A1%D0%B0%D0%BB%D1%96%D0%B3%D0%BE%D1%80%D1%81%D0%BAi_%D1%80%D0%B0%D1%91%D0%BD%C2%BB2004',
    regionId: 10,
    class: 'circle starobin',
  },
  {
    id: 93,
    dataId: 92,
    title: 'д.Ходыка',
    dataTooltip: 'Ходыка',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 33 двора и убили 131 жителя. После войны деревня не восстановилась',
    img: './image/chodyka.jpg',
    link: 'http://db.narb.by/search/4925',
    regionId: 10,
    class: 'circle chodyka',
  },
  {
    id: 94,
    dataId: 94,
    title: 'д.Сухая Миля',
    dataTooltip: 'Сухая Миля',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 24 двора и убили 28 жителей. После войны деревня не восстановилась',
    img: './image/suhayamilya.jpg',
    link: 'http://db.narb.by/search/4612',
    regionId: 10,
    class: 'circle suhmil',
  },
  {
    id: 95,
    dataId: 95,
    title: 'д.Рог',
    dataTooltip: 'Рог',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 123 двора и убили 57 жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3978',
    regionId: 10,
    class: 'circle rog',
  },
  {
    id: 96,
    dataId: 96,
    title: 'д.Старчицы',
    dataTooltip: 'Старчицы',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 121 двор и убили 45 жителей.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/3978',
    regionId: 11,
    class: 'circle starchicy',
  },
  {
    id: 97,
    dataId: 97,
    title: 'д.Рассвет',
    dataTooltip: 'Рассвет',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 21 двор и убили 23 жителя.',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/8464',
    regionId: 11,
    class: 'circle rassvet',
  },
  {
    id: 98,
    dataId: 98,
    title: 'г.п. Красная Слобода',
    dataTooltip: 'Красная Слобода',
    desc: 'После оккупации евреев Красной Слободы согнали в гетто, которое просуществовало до весны 1942 года. Осенью 1941 года немцы провели первый массовый расстрел евреев посёлка, убив около 900 человек.',
    img: './image/krasslob.jpg',
    link: 'https://ru.wikipedia.org/wiki/%D0%A5%D0%BE%D0%BB%D0%BE%D0%BA%D0%BE%D1%81%D1%82_%D0%B2_%D0%A1%D0%BE%D0%BB%D0%B8%D0%B3%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%BC_%D1%80%D0%B0%D0%B9%D0%BE%D0%BD%D0%B5#cite_note-autogenerated1-20',
    regionId: 11,
    class: 'circle krasslob',
  },
  {
    id: 99,
    dataId: 99,
    title: 'д. Погост',
    dataTooltip: 'Погост',
    desc: 'В гетто в деревне Погост (конец июня — 25 августа 1941) были замучены и убиты не менее 440 евреев.',
    img: './image/pogost.jpg',
    link: 'https://ru.wikipedia.org/wiki/%D0%A5%D0%BE%D0%BB%D0%BE%D0%BA%D0%BE%D1%81%D1%82_%D0%B2_%D0%A1%D0%BE%D0%BB%D0%B8%D0%B3%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%BC_%D1%80%D0%B0%D0%B9%D0%BE%D0%BD%D0%B5#cite_note-autogenerated1-20',
    regionId: 10,
    class: 'circle pogost',
  },
  {
    id: 100,
    dataId: 100,
    title: 'д. Гондарево',
    dataTooltip: 'Гондарево',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 16 дворов и убили 60 жителей. После войны деревня не восстановилась',
    img: './image/gondarevo.jpg',
    link: 'http://db.narb.by/search/962',
    regionId: 12,
    class: 'circle gondarevo',
  },
  {
    id: 101,
    dataId: 101,
    title: 'д.Красная Сторонка',
    dataTooltip: 'Красная Сторонка',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 24 двора и убили 75 жителей. ',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2276',
    regionId: 12,
    class: 'circle krasstor',
  },
  {
    id: 102,
    dataId: 102,
    title: 'д.Левище',
    dataTooltip: 'Левище',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 12 дворов и убили 45 жителей.После войны деревня не восстановилась ',
    img: './image/lewische.jpg',
    link: 'http://db.narb.by/search/2499',
    regionId: 12,
    class: 'circle lewische',
  },
  {
    id: 103,
    dataId: 103,
    title: 'д.Старево',
    dataTooltip: 'Старево',
    desc: 'Во время Великой Отечественной войны немецкие оккупанты сожгли 28 дворов и убили 43 жителя. ',
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/4468',
    regionId: 12,
    class: 'circle starevo',
  },
  {
    id: 104,
    dataId: 104,
    title: 'г.Слуцк',
    dataTooltip: 'Слуцк',
    desc: `В июне 1941 года в городе Слуцке на территории первого военного городка был создан лагерь для советских военнопленных. С 1942 года в лагерь стали свозить мирных жителей не только из городов Беларуси, но и оккупированных областей России: Орловской, Брянской, Тверской, Калужской, Курской, Псковской, Смоленской. Семьями в товарных вагонах их привозили фашисты в Слуцк. В основном это были женщины, дети и старики… Трудоспособных немцы отправляли в концлагеря в Польшу, Прибалтику, Германию. Больные и слабые оставались в Слуцке, многие из них гибли от голода и холода. Хоронили умерших на территории лагеря.
    По данным специальной комиссии с июня 1941 по март 1944 года в лагере советских военнопленных и мирных граждан было замучено, расстреляно, умерло от ран и эпидемий более 28 тысяч человек. `,
    img: './image/slutsk.jpg',
    link: 'https://slutsk.fpb.1prof.by/publications/news/v-slucke-k-pamyatnomu-znaku-uznikam-lagerya-sovetskix-voennoplennyx-i-mirnyx-grazhdan-vozlozhili-cvety/',
    regionId: 12,
    class: 'circle slutsk',
  },
  {
    id: 105,
    dataId: 105,
    title: 'д.Адамово',
    dataTooltip: 'Адамово',
    desc: `Во время Великой Отечественной войны немецкие оккупанты сожгли 52 двора и убили 213 жителей.`,
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/22',
    regionId: 13,
    class: 'circle adamovo',
  },
  {
    id: 106,
    dataId: 106,
    title: 'д.Греск',
    dataTooltip: 'Греск',
    desc: ` Деревня находилась под немецкой оккупацией 3 года — с 27 июня 1941 года до 1 июля 1944 года.Евреев местечка согнали в гетто, а 18 декабря 1941 года убили всех ещё оставшихся в живых.Расстрел произошел в 1,5 километрах от Греска в урочище Гаек — это лес на окраине деревни в направлении на Грозово (сейчас на этом месте находятся карьеры асфальтобетонного завода «Гаек»). Перед смертью евреев заставили раздеться, и после убийства одежду и вещи евреев разобрали полицаи.`,
    img: './image/gresk.jpg',
    link: 'http://db.narb.by/search/22',
    regionId: 13,
    class: 'circle gresk',
  },
  {
    id: 107,
    dataId: 107,
    title: 'д.Переходы',
    dataTooltip: 'Переходы',
    desc: `Деревня Переходы (не восстановлена). Находилась в полуто­ра километрах южнее деревни Жилин Брод. В 24 могилах похо­ронено 116 жителей. На могилах установлены обелиски. `,
    img: './image/perehody.jpg',
    link: 'http://db.narb.by/search/3495',
    regionId: 13,
    class: 'circle perehody',
  },
  {
    id: 108,
    dataId: 108,
    title: 'д.Жилин Брод',
    dataTooltip: 'Жилин Брод',
    desc: `В 1972 г. в деревне Жилин Брод в память о погибших жителях деревень Березинец, Жилин Брод, Задовба, Крушник, Поликаровка и Фадеевка установлена скульптура скорбящей матери.Эти населенные пункты находились рядом друг с другом, всего в них было убито более 100 человек`,
    img: './image/perehody.jpg',
    link: 'http://db.narb.by/search/3495',
    regionId: 13,
    class: 'circle zhbrod',
  },
  {
    id: 109,
    dataId: 109,
    title: 'д.Большие Прусы',
    dataTooltip: 'Большие Пруссы',
    desc: `Во время Великой Отечественной войны немецкие оккупанты сожгли 121 двор и убито 255 жителей.`,
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/341',
    regionId: 14,
    class: 'circle prussy',
  },
  {
    id: 110,
    dataId: 110,
    title: 'д.Грозово',
    dataTooltip: 'Грозово',
    desc: `В годы оккупации в деревне находилось гетто. Было убито и замучено более 400 человек`,
    img: './image/grozovo.jpg',
    link: 'http://db.narb.by/search/341',
    regionId: 14,
    class: 'circle grozovo',
  },
  {
    id: 111,
    dataId: 111,
    title: 'д.Жаволки',
    dataTooltip: 'Жаволки',
    desc: `В феврале 1943 года фашистские захватчики уничтожили тут 512 человек - в основном стариков, женщин и детей.`,
    img: './image/zhavolki.jpg',
    link: 'http://db.narb.by/search/1410',
    regionId: 14,
    class: 'circle zhavolki',
  },
  {
    id: 112,
    dataId: 112,
    title: 'д.Колодезное',
    dataTooltip: 'Колодезное',
    desc: `Во время Великой Отечественной войны немецкие оккупанты сожгли 57 дворов и убито 196 жителей.`,
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/2108',
    regionId: 14,
    class: 'circle kolodez',
  },
  {
    id: 113,
    dataId: 113,
    title: 'д.Масевичи',
    dataTooltip: 'Масевичи',
    desc: `Во время Великой Отечественной войны немецкие оккупанты сожгли 32 дворов и убито 130 жителей. Деревня не восстановилась`,
    img: './image/masevichi.jpg',
    link: 'http://db.narb.by/search/2821',
    regionId: 14,
    class: 'circle masevichi',
  },
  {
    id: 114,
    dataId: 114,
    title: 'д.Песочное',
    dataTooltip: 'Песочное',
    desc: `Во время Великой Отечественной войны немецкие оккупанты сожгли 65 дворов и убито 172 жителя.`,
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6923',
    regionId: 14,
    class: 'circle pesochnoe',
  },
  {
    id: 115,
    dataId: 115,
    title: 'д.Тимковичи',
    dataTooltip: 'Тимковичи',
    desc: `В годы оккупации в деревне находилось гетто. Было убито и замучено около 1000 человек`,
    img: './image/voyna.jpg',
    link: 'http://db.narb.by/search/6928',
    regionId: 14,
    class: 'circle timkovichi',
  },
  {
    id: 116,
    dataId: 116,
    title: 'г.Копыль',
    dataTooltip: 'Копыль',
    desc: `В гетто города Копыль (конец июня 1941 — 22 июля 1942) были замучены и убиты 3500 евреев`,
    img: './image/kopyl.jpg',
    link: 'http://db.narb.by/search/6928',
    regionId: 14,
    class: 'circle kopyl',
  },
];
